sudo: required
services:
  - docker

before_install:
  - docker build -t mihalytari/react-image -f Dockerfile.dev .

script:
  - docker run mihalytari/react-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-image"
  env: "ReactImage-env"
  bucket_name: "elasticbeanstalk-us-east-2-151932697359"
  bucket_path: "react-image"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"